[package]
name = "heist-rusters"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.3"
gdrusthelper = { git = "https://github.com/Pyzyryab/gdrust-helper" }